// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB11weNoEIxM0QfB-qYifKEVuwrKepX1jQ',
    appId: '1:440440539648:web:fc4a8023be73e9331026e5',
    messagingSenderId: '440440539648',
    projectId: 'kanote-68479',
    authDomain: 'kanote-68479.firebaseapp.com',
    storageBucket: 'kanote-68479.appspot.com',
    measurementId: 'G-VW8EHEXYV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvesz9EzbSRimtzfyaSeAO6IHjZM9v-Rw',
    appId: '1:440440539648:android:0960d7670d86bf191026e5',
    messagingSenderId: '440440539648',
    projectId: 'kanote-68479',
    storageBucket: 'kanote-68479.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEWdCFUsp64hFSVsI0qTxwVViQ_Q_X-4E',
    appId: '1:440440539648:ios:4535504a02900a551026e5',
    messagingSenderId: '440440539648',
    projectId: 'kanote-68479',
    storageBucket: 'kanote-68479.appspot.com',
    iosClientId: '440440539648-lh1ukk2o490j7lsmt8g7bbu9g65c10aa.apps.googleusercontent.com',
    iosBundleId: 'com.kanote.kanoteApp',
  );
}
